name: Telematics Login Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Chrome and ChromeDriver
      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Step 5: Run the script
      - name: Run telematics login check
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: python telematics_check.py

      # Step 6: Upload logs and screenshots as artifacts
      - name: Upload logs and screenshots
        uses: actions/upload-artifact@v4
        with:
          name: telematics-logs
          path: logs/
